version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    # depends_on:
    #   - db
  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - "8889:80"
  #   environment:
  #     # PMA_ABITRARY: 1
  #     PMA_HOST: db
  #   depends_on:
  #     - db  
  #     # nouvelle utilisateur
  #     # MYSQL_USER: user
  #     # MYSQL_PASSWORD: mypassword   
  # db:
  #   # platform: linux/x86_64
  #   image: mysql:latest
  #   ports:
  #     - '5506:3306'
  #   # command: --default-authentication-pplugin=mysql_native_password
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_USER: root
  #     MYSQL_ROOT_PASSWORD: 12345678
  #     MYSQL_PASSWORD: 12345678
  #   # ports:
  #   #   - '3306:3306'  
  #   # container_name: pgadmin4
  #   # image: dpage/pgadmin4
  #   # restart: always
  #   # environment:
  #   #   PGADMIN_DEFAULT_EMAIL: root@root.com
  #   #   PGADMIN_DEFAULT_PASSWORD: root
  #   # ports:
  #   #   - "5000:80"
